@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"
set "ROOT=%~dp0..\"

rem MSVC x86, same ABI as L4D2 / Necola. Do not fall back to MinGW.
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" set "VSWHERE=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" (
  echo ERROR: vswhere.exe not found. Install VS 2022 Build Tools with C++ workload.
  exit /b 1
)
set "VSINSTALL="
for /f "usebackq delims=" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALL=%%I"
if not defined VSINSTALL (
  echo ERROR: MSVC x86 toolset not found. Install Visual Studio C++ tools ^(x86^).
  exit /b 1
)
call "%VSINSTALL%\VC\Auxiliary\Build\vcvarsall.bat" x86 >nul
if errorlevel 1 (
  echo ERROR: vcvarsall.bat x86 failed
  exit /b 1
)
where cl >nul 2>&1
if errorlevel 1 (
  echo ERROR: cl.exe not on PATH after vcvarsall x86
  exit /b 1
)
echo Using MSVC x86:
cl 2>&1 | findstr /i "Version Compiler"

set "DLCVER=0.0.0-dev"
if exist "%ROOT%VERSION.txt" (
  for /f "usebackq tokens=1,* delims==" %%A in (`findstr /b /i /c:"semver=" "%ROOT%VERSION.txt"`) do set "DLCVER=%%B"
)
set "DLCVER=!DLCVER: =!"
if "!DLCVER!"=="" set "DLCVER=0.0.0-dev"
echo Skeeto version: !DLCVER!
(
  echo #pragma once
  echo // Auto-generated by build.bat from VERSION.txt - do not edit.
  echo #define SKEETO_VERSION "!DLCVER!"
  echo #define SKEETO_VERSION_W L"!DLCVER!"
) > "%~dp0skeeto_version.generated.h"

set "OUTDIR=%ROOT%dist"
if not exist "%OUTDIR%" mkdir "%OUTDIR%"
set "OUT=%OUTDIR%\skeeto.dll"
set "OBJ=%~dp0obj"
if not exist "%OBJ%" mkdir "%OBJ%"

cl /nologo /LD /MT /O2 /Oy- /EHsc /std:c++17 /utf-8 /W3 /wd4100 /wd4244 /wd4458 /wd4996 ^
  /DWIN32 /D_CRT_SECURE_NO_WARNINGS ^
  /Fe"%OUT%" /Fo"%OBJ%\\" /Fd"%OBJ%\skeeto.pdb" ^
  "%~dp0skeeto_proxy.cpp" ^
  "%~dp0skeeto_style.cpp" ^
  /link /MACHINE:X86 /INCREMENTAL:NO /IMPLIB:"%OBJ%\skeeto.lib" ^
  user32.lib kernel32.lib gdi32.lib gdiplus.lib ole32.lib
if errorlevel 1 exit /b 1

echo Built %OUT%
exit /b 0
